---

- hosts: all
  become: true
  tasks:


  - name: install php and apache2 packages for Ubntu 
    apt:
      update_cache: yes
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
 

  - name: install php and httpd packages for CentOS 
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
 

