---


- hosts: all
  become: true
  pre_tasks: 


  - name: install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"


  - name: install updates (Ubuntu)
    tags: always 
    apt:
      update_cache: yes
      upgrade: dist
    when: ansible_distribution == "Ubuntu"



- hosts: web_servers
  become: true
  tasks:

  - name: install httpd pachage (CentOS)
    tags: centos,httpd,apache
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install apach2 pachage (Ubuntu)
    tags: ubuntu,apache2,apache
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: copy html file for site
    tags: apache,apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (CentOS)
    tags: centos,db,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb server
    tags: ubuntu,db,mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"



- hosts: file_servers
  become: true
  tasks:

  - name: install samba file server
    tags: centos,ubuntu,smaba
    package:
      name: samba
      state: latest

